import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Check, PenLine, RotateCcw, ShieldCheck, Smartphone, Type, X } from 'lucide-react';
import type { Agreement, Participant, SignatureInput } from '@bytecrunch/contracts-domain';
import { BusyMark } from './ReviewWorkspace';

export function SignatureCeremony({ agreement, signer, busy, onClose, onSign }: { agreement: Agreement; signer: Participant; busy: boolean; onClose: () => void; onSign: (signature: SignatureInput) => void }) {
  const [method, setMethod] = useState<'typed' | 'drawn'>('typed'); const [typedName, setTypedName] = useState(signer.name); const [intent, setIntent] = useState(false); const [hasDrawing, setHasDrawing] = useState(false); const canvas = useRef<HTMLCanvasElement>(null); const drawing = useRef(false);
  useEffect(() => { const element = canvas.current; if (!element) return; const rect = element.getBoundingClientRect(); const scale = window.devicePixelRatio || 1; element.width = Math.max(1, Math.round(rect.width * scale)); element.height = Math.round(190 * scale); const context = element.getContext('2d'); if (context) { context.scale(scale, scale); context.lineCap = 'round'; context.lineJoin = 'round'; context.lineWidth = 2.4; context.strokeStyle = '#111111'; } }, [method]);
  function point(event: React.PointerEvent<HTMLCanvasElement>) { const element = canvas.current!; const rect = element.getBoundingClientRect(); return { x: event.clientX - rect.left, y: event.clientY - rect.top }; }
  function start(event: React.PointerEvent<HTMLCanvasElement>) { const context = canvas.current?.getContext('2d'); if (!context) return; event.currentTarget.setPointerCapture(event.pointerId); const next = point(event); context.beginPath(); context.moveTo(next.x, next.y); drawing.current = true; }
  function move(event: React.PointerEvent<HTMLCanvasElement>) { if (!drawing.current) return; const context = canvas.current?.getContext('2d'); if (!context) return; const next = point(event); context.lineTo(next.x, next.y); context.stroke(); setHasDrawing(true); }
  function finish() { drawing.current = false; }
  function clear() { const element = canvas.current; const context = element?.getContext('2d'); if (element && context) context.clearRect(0, 0, element.width, element.height); setHasDrawing(false); }
  function submit() { if (!intent || typedName.trim().length < 2 || (method === 'drawn' && !hasDrawing)) return; onSign(method === 'typed' ? { method, typedName: typedName.trim(), imageDataUrl: null } : { method, typedName: typedName.trim(), imageDataUrl: canvas.current!.toDataURL('image/png') }); }
  return <div className="signature-overlay" role="presentation"><section className="signature-ceremony" role="dialog" aria-modal="true" aria-labelledby="signature-title"><header><div><span className="bc-eyebrow bc-text-blue">// SIGNATURE CEREMONY</span><h2 id="signature-title">Sign {agreement.title}</h2></div><button className="icon-button" aria-label="Close signing" onClick={onClose}><X /></button></header><div className="signature-layout"><div className="signature-summary"><ShieldCheck /><h3>You’re signing this exact revision.</h3><p>Review the document, create your signature, then confirm your intent. Your signature is bound to the content fingerprint below.</p><dl><div><dt>Signer</dt><dd>{signer.name}</dd></div><div><dt>Capacity</dt><dd>{signer.capacity?.replaceAll('_', ' ') ?? signer.title ?? 'Signatory'}</dd></div><div><dt>Revision</dt><dd>R{String(agreement.revision).padStart(2, '0')}</dd></div><div><dt>Fingerprint</dt><dd>{agreement.contentSha256.slice(0, 16)}…{agreement.contentSha256.slice(-8)}</dd></div></dl><div className="mobile-sign-note"><Smartphone /><span><strong>Signing on your phone?</strong> This screen is touch-enabled—open the secure invitation on your phone and draw with your finger.</span></div></div><div className="signature-maker"><div className="signature-tabs" role="tablist"><button className={method === 'typed' ? 'active' : ''} onClick={() => setMethod('typed')}><Type /> Type</button><button className={method === 'drawn' ? 'active' : ''} onClick={() => setMethod('drawn')}><PenLine /> Draw</button></div><label>Full legal name<input value={typedName} onChange={(event) => setTypedName(event.target.value)} /></label>{method === 'typed' ? <div className="typed-signature" aria-label={`Signature preview for ${typedName}`}>{typedName || 'Your signature'}</div> : <div className="draw-signature"><canvas ref={canvas} aria-label="Draw your signature" onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish} /><button className="text-button" onClick={clear}><RotateCcw /> Clear</button></div>}<label className="check-field"><input type="checkbox" checked={intent} onChange={(event) => setIntent(event.target.checked)} /><span><strong>I intend to sign this agreement electronically</strong><small>I have reviewed revision R{String(agreement.revision).padStart(2, '0')} and adopt the signature above as my signature.</small></span></label><p className="development-witness">Local development witness — not a certified or qualified electronic-signature provider.</p><button disabled={busy || !intent || typedName.trim().length < 2 || (method === 'drawn' && !hasDrawing)} className="button button-accent signature-submit" onClick={submit}>{busy ? <><BusyMark /> Recording signature…</> : <>Adopt and sign <ArrowRight /></>}</button></div></div></section></div>;
}

export function SignatureBlocks({ agreement }: { agreement: Agreement }) {
  const partyOrder = new Map(agreement.parties.map((party, index) => [party.id, index])); const signers = agreement.participants.filter((participant) => participant.role === 'signatory' && participant.required).sort((a, b) => (partyOrder.get(a.partyId ?? '') ?? 999) - (partyOrder.get(b.partyId ?? '') ?? 999)); if (signers.length === 0) return null;
  return <section className="document-signatures" aria-label="Signature blocks"><div>{signers.map((signer) => { const party = signer.partyId ? agreement.parties.find((item) => item.id === signer.partyId) : undefined; return <article className={signer.signature ? 'signed' : ''} key={signer.id}><header><span>Signed for and on behalf of</span><strong>{party?.entity.legalName ?? 'Legal entity pending'}</strong></header><div className={`signature-mark ${signer.signature?.method === 'drawn' ? 'drawn' : ''}`}>{signer.signature?.method === 'drawn' && signer.signature.imageDataUrl ? <img src={signer.signature.imageDataUrl} alt={`Signature of ${signer.signature.typedName}`} /> : signer.signature ? <span>{signer.signature.typedName}</span> : <i />}</div><small className="signature-line-label">Signature</small><dl><div><dt>Name</dt><dd>{signer.signature?.typedName ?? signer.name}</dd></div><div><dt>Title / capacity</dt><dd>{signer.title ?? signer.capacity?.replaceAll('_', ' ') ?? 'Authorized signatory'}</dd></div><div><dt>Date</dt><dd>{signer.signature ? new Date(signer.signature.signedAt).toLocaleDateString() : '—'}</dd></div></dl>{signer.signature && <footer>Electronic signature record · {signer.signature.signedContentSha256.slice(0, 12)}…</footer>}</article>; })}</div></section>;
}

export function NextActionBanner({ eyebrow = '// NEXT ACTION', title, body, waiting = false, action }: { eyebrow?: string; title: string; body: string; waiting?: boolean; action?: { label: string; onClick: () => void; busy?: boolean } }) {
  return <section className={`next-action ${waiting ? 'waiting' : ''}`}><div className="next-action-index">{waiting ? '··' : '→'}</div><div><span className="bc-eyebrow">{eyebrow}</span><h2>{title}</h2><p>{body}</p></div>{action && <button disabled={action.busy} className="button button-accent" onClick={action.onClick}>{action.busy ? <><BusyMark /> Working…</> : <>{action.label} <ArrowRight /></>}</button>}</section>;
}
